### ISSUE TITLE
Theme Question

### ISSUE THREAD

**Issue by Technologx** [1hakr/AnExplorer#51]
So is there a way to make this to were users could create separate apps that are themes that this app could pick up and apply?

**Comment by 1hakr** [comment]
Yes. This should be possible. Currently the theme is take from settings which can be extended from another app aswell

**Comment by Technologx** [comment]
Do you think you could implement something like this? I mean if you could your app would be even more popular than the other file explorer's out there.

**Comment by 1hakr** [comment]
Yes i could but this is a delight feature. Currently im focusing on completing the features

**Comment by Technologx** [comment]
I don't blame you I was just throwing a idea atcha that other file explorer's don't have and developers/graphic designers would love.

**Comment by enwokoma** [comment]
Ya ya @Technologx .. I totally agree with you 100%. Only problem I see with this project is that its development is very slow... He should focus more on it. People like me for example, am working on some features for this project like an internal audio and video player, an internal pdf viewer and editor and an internal Image Viewer..
I only discontinued working on it recently and offered it to Amaze File Manager project because I felt @1hakr  might have discontinued this [AnExplorer](https://github.com/1hakr/AnExplorer) project... We really need to move fast by following the latest trends.

Least I forget, @1hakr , hope you know Google is beginning to remove apps with accessibility services and AnExplorer has this service, so I don't know how u choose to go about it before Google takes your app down!
Have a pleasant day...

**Comment by 1hakr** [comment]
@enwokoma i have been busy with my own startup for sometime now. Because of that i was not able to do much in AnExplorer. Rest assured, i have some good plans to take it forward soon. I have seen that you have released a fork of this app on playstore, i would have loved to see a PR with the features you mentioned. And yes i will be fixing the accessibility issue soon.

**Comment by enwokoma** [comment]
@1hakr .. Ok. Cool! I would see what I can do about this, let me get my team in order!
Do have a nice day...
